### ISSUE TITLE
iFan03 shows boolean actions for light and fan with same name in visual editor

### ISSUE THREAD

**Issue by GsakuL** [emontnemery/hatasmota#158]
This is "just" a visual issue. Functional it all works.

As per tasmota instructions I added my iFan03 via TasmotaDiscovery (`SetOption19 0`) and used the Tasmota Integration.
The device is picked up correctly, and I see all entities.
Yet when making an automation and selection Action->Device->[the iFan] i get the options off/on/toggle twice: once for the fan and once for the light, with the exact same name:
![image](https://user-images.githubusercontent.com/6844160/172021413-b12b479a-0f5c-4876-8726-191e6301d7df.png)

The first triplet seems to be always for the fan, as i amused from the device overview:
![image](https://user-images.githubusercontent.com/6844160/172021511-76f58b01-2662-4029-9391-93e1454e5c7e.png)

It is obvious in the YAML editor only (see below). For someone using the visual editor not so much (refer to first image).
```YAML
...
    sequence:
      - type: toggle
        device_id: 3ee2e1fa9c95a0bf51c0b18114430e99
        entity_id: light.ifan03
        domain: light
...
```

My 'Config -> Other' Setup on the iFan itself:
![image](https://user-images.githubusercontent.com/6844160/172021628-76f0c786-6f79-442d-ad62-fd76301c19ae.png)

'Config -> MQTT'
![image](https://user-images.githubusercontent.com/6844160/172021694-f9b1ee57-5c70-4d26-8452-e2964cc4aa59.png)
